// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "url-shortener/shortenurl/model"

	mock "github.com/stretchr/testify/mock"
)

// IURLService is an autogenerated mock type for the IURLService type
type IURLService struct {
	mock.Mock
}

// Create provides a mock function with given fields: url
func (_m *IURLService) Create(url string) (*model.ShortURL, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.ShortURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ShortURL, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ShortURL); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: code
func (_m *IURLService) Delete(code string) error {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: code
func (_m *IURLService) Get(code string) (*model.ShortURL, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.ShortURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ShortURL, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ShortURL); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: code, newURL
func (_m *IURLService) Update(code string, newURL string) (*model.ShortURL, error) {
	ret := _m.Called(code, newURL)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.ShortURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.ShortURL, error)); ok {
		return rf(code, newURL)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.ShortURL); ok {
		r0 = rf(code, newURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(code, newURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIURLService creates a new instance of IURLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IURLService {
	mock := &IURLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
