// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "url-shortener/shortenurl/model"

	mock "github.com/stretchr/testify/mock"
)

// UrlRepo is an autogenerated mock type for the UrlRepo type
type UrlRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: url
func (_m *UrlRepo) Create(url *model.ShortURL) (int, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.ShortURL) (int, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(*model.ShortURL) int); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*model.ShortURL) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByCode provides a mock function with given fields: code
func (_m *UrlRepo) DeleteByCode(code string) error {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByCode provides a mock function with given fields: code
func (_m *UrlRepo) GetByCode(code string) (*model.ShortURL, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *model.ShortURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ShortURL, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ShortURL); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementAccessCount provides a mock function with given fields: code
func (_m *UrlRepo) IncrementAccessCount(code string) error {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAccessCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateURL provides a mock function with given fields: code, newURL
func (_m *UrlRepo) UpdateURL(code string, newURL string) error {
	ret := _m.Called(code, newURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(code, newURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUrlRepo creates a new instance of UrlRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlRepo {
	mock := &UrlRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
